import { createHash } from 'node:crypto';
import {
  createReadStream,
  existsSync,
  mkdirSync,
  readFileSync,
  rmSync,
  statSync,
  writeFileSync,
} from 'node:fs';
import path from 'node:path';
import matter from 'gray-matter';
import { PRODUCTION_SITE_URL } from '../../site.config';
import type {
  FeaturedMedia,
  MigrationManifest,
  PageManifestEntry,
  PostManifestEntry,
  StoryManifestEntry,
  SourceFingerprint,
} from './types';

export function sha256(value: string | Buffer): string {
  return createHash('sha256').update(value).digest('hex');
}

export async function fingerprintSource(
  filePath: string,
): Promise<SourceFingerprint> {
  const hash = createHash('sha256');
  const stream = createReadStream(filePath);
  for await (const chunk of stream) hash.update(chunk as Buffer);

  return {
    filename: path.basename(filePath),
    bytes: statSync(filePath).size,
    sha256: hash.digest('hex'),
  };
}

export function normalizedTextChecksum(html: string): string {
  const text = html
    .replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi, ' ')
    .replace(/<[^>]+>/g, ' ')
    .replace(/&nbsp;/gi, ' ')
    .replace(/&amp;/gi, '&')
    .replace(/&lt;/gi, '<')
    .replace(/&gt;/gi, '>')
    .replace(/\s+/g, ' ')
    .normalize('NFC')
    .trim();

  return sha256(text);
}

function assertGeneratedDirectory(repoRoot: string, directory: string): void {
  const root = path.resolve(repoRoot);
  const target = path.resolve(directory);
  const allowed = [
    path.resolve(repoRoot, 'src', 'content', 'posts'),
    path.resolve(repoRoot, 'src', 'content', 'pages'),
    path.resolve(repoRoot, 'src', 'content', 'stories'),
    path.resolve(repoRoot, 'public', 'blog'),
    path.resolve(repoRoot, 'public', 'web-stories'),
  ];

  if (!target.startsWith(`${root}${path.sep}`) || !allowed.includes(target)) {
    throw new Error(
      `Refusing to replace unexpected generated directory: ${target}`,
    );
  }
}

export function resetGeneratedDirectory(
  repoRoot: string,
  directory: string,
): void {
  assertGeneratedDirectory(repoRoot, directory);
  if (existsSync(directory))
    rmSync(directory, { force: true, recursive: true });
  mkdirSync(directory, { recursive: true });
}

export function removePreviousRootAliasPages(repoRoot: string): void {
  const manifestPath = path.join(repoRoot, 'migration', 'manifest.json');
  if (!existsSync(manifestPath)) return;

  const previous = JSON.parse(readFileSync(manifestPath, 'utf8')) as {
    posts?: Array<{ aliases?: unknown }>;
    pages?: Array<{ aliases?: unknown }>;
    stories?: Array<{ aliases?: unknown }>;
  };
  const entries = [
    ...(previous.posts ?? []),
    ...(previous.pages ?? []),
    ...(previous.stories ?? []),
  ];

  for (const entry of entries) {
    if (!Array.isArray(entry.aliases)) continue;
    for (const alias of entry.aliases) {
      if (typeof alias !== 'string' || !/^\/[^/]+\.html$/i.test(alias))
        continue;
      const target = path.resolve(repoRoot, 'public', alias.slice(1));
      const publicRoot = path.resolve(repoRoot, 'public');
      if (!target.startsWith(`${publicRoot}${path.sep}`) || !existsSync(target))
        continue;
      const source = readFileSync(target, 'utf8');
      if (source.includes('<!-- Generated migration alias. -->'))
        rmSync(target);
    }
  }
}

function writeGeneratedMarkdown(
  filePath: string,
  frontmatter: Record<string, unknown>,
  html: string,
): void {
  const notice =
    '<!-- Generated by scripts/migrate-wordpress. Do not edit by hand. -->';
  const rendered = matter.stringify(
    `${notice}\n\n${html.trim()}\n`,
    frontmatter,
  );
  writeFileSync(filePath, rendered.replaceAll('\r\n', '\n'), 'utf8');
}

export function writePost(options: {
  repoRoot: string;
  manifest: PostManifestEntry;
  excerpt: string;
  html: string;
}): void {
  const postDir = path.join(options.repoRoot, 'src', 'content', 'posts');
  const { manifest } = options;
  writeGeneratedMarkdown(
    path.join(postDir, `${manifest.slug}.md`),
    {
      aliases: manifest.aliases,
      canonicalPath: manifest.canonicalPath,
      categories: manifest.categories,
      excerpt: options.excerpt,
      featuredMedia: manifest.featuredMedia,
      originalStatus: manifest.originalStatus,
      publishedAt: manifest.publishedAt,
      slug: manifest.slug,
      sourceChecksum: manifest.sourceChecksum,
      tags: manifest.tags,
      title: manifest.title,
      updatedAt: manifest.updatedAt,
      wasMembersOnly: manifest.wasMembersOnly,
      wpId: manifest.wpId,
    },
    options.html,
  );
}

export function writePage(options: {
  repoRoot: string;
  manifest: PageManifestEntry;
  excerpt: string;
  html: string;
  featuredMedia: FeaturedMedia | null;
  updatedAt: string;
}): void {
  const pageDir = path.join(options.repoRoot, 'src', 'content', 'pages');
  const { manifest } = options;
  writeGeneratedMarkdown(
    path.join(pageDir, `${manifest.slug}.md`),
    {
      aliases: manifest.aliases,
      canonicalPath: manifest.canonicalPath,
      excerpt: options.excerpt,
      featuredMedia: options.featuredMedia,
      originalStatus: 'publish',
      pageKind: 'about',
      slug: manifest.slug,
      sourceChecksum: manifest.sourceChecksum,
      title: manifest.title,
      updatedAt: options.updatedAt,
      wpId: manifest.wpId,
    },
    options.html,
  );
}

export function writeStory(options: {
  repoRoot: string;
  story: StoryManifestEntry;
  excerpt: string;
  poster: string | null;
  publishedAt: string;
  updatedAt: string;
  ampHtml: string;
  comparisonNotes: string[];
  omittedAssets: string[];
}): void {
  const storyDir = path.join(options.repoRoot, 'src', 'content', 'stories');
  const publicStoryDir = path.join(
    options.repoRoot,
    'public',
    'web-stories',
    options.story.slug,
  );
  mkdirSync(publicStoryDir, { recursive: true });

  writeFileSync(
    path.join(storyDir, `${options.story.slug}.json`),
    `${JSON.stringify(
      {
        aliases: options.story.aliases,
        ampSourcePath: `/web-stories/${options.story.slug}/story.html`,
        canonicalPath: options.story.canonicalPath,
        excerpt: options.excerpt,
        legacyComparison: {
          decision: options.story.comparisonDecision,
          notes: options.comparisonNotes,
          omittedAssets: options.omittedAssets,
        },
        legacyPageCount: options.story.legacyPageCount,
        legacyWpId: options.story.legacyWpId,
        modernPageCount: options.story.modernPageCount,
        modernWpId: options.story.modernWpId,
        poster: options.poster,
        publishedAt: options.publishedAt,
        slug: options.story.slug,
        sourceChecksum: options.story.sourceChecksum,
        artifactChecksum: options.story.artifactChecksum,
        title: options.story.title,
        transcript: options.story.transcript,
        updatedAt: options.updatedAt,
      },
      null,
      2,
    )}\n`,
    'utf8',
  );
  writeFileSync(
    path.join(publicStoryDir, 'story.html'),
    options.ampHtml.replaceAll('\r\n', '\n'),
    'utf8',
  );
}

export function writeAliasPage(options: {
  repoRoot: string;
  alias: string;
  canonicalPath: string;
  title: string;
}): void {
  const cleanAlias = options.alias.replace(/^\/+|\/+$/g, '');
  if (
    !cleanAlias ||
    cleanAlias.split('/').some((segment) => segment === '..')
  ) {
    throw new Error(`Unsafe alias path: ${options.alias}`);
  }

  const isHtmlAlias = cleanAlias.toLocaleLowerCase('en-US').endsWith('.html');
  const outputPath = isHtmlAlias
    ? path.join(options.repoRoot, 'public', ...cleanAlias.split('/'))
    : path.join(
        options.repoRoot,
        'public',
        ...cleanAlias.split('/'),
        'index.html',
      );
  mkdirSync(path.dirname(outputPath), { recursive: true });
  const escapedTitle = options.title
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;');
  const canonicalTarget = path.resolve(
    options.repoRoot,
    'public',
    options.canonicalPath.replace(/^\//, ''),
  );
  const relativeTarget = path
    .relative(path.dirname(outputPath), canonicalTarget)
    .replaceAll('\\', '/');
  const navigationTarget = relativeTarget.startsWith('.')
    ? relativeTarget
    : `./${relativeTarget}`;
  const escapedNavigation = navigationTarget
    .replaceAll('&', '&amp;')
    .replaceAll('"', '&quot;');
  const escapedCanonical = `${PRODUCTION_SITE_URL}${options.canonicalPath}`
    .replaceAll('&', '&amp;')
    .replaceAll('"', '&quot;');
  const html = `<!doctype html>
<!-- Generated migration alias. -->
<html lang="zh-Hant">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="robots" content="noindex,follow">
    <meta http-equiv="refresh" content="0;url=${escapedNavigation}">
    <link rel="canonical" href="${escapedCanonical}">
    <title>${escapedTitle}｜數位引擎</title>
  </head>
  <body>
    <p>頁面已搬遷至 <a href="${escapedNavigation}">${escapedTitle}</a>。</p>
  </body>
</html>
`;
  writeFileSync(outputPath, html, 'utf8');
}

export function writeManifest(
  repoRoot: string,
  manifest: MigrationManifest,
): void {
  const migrationDir = path.join(repoRoot, 'migration');
  mkdirSync(migrationDir, { recursive: true });
  writeFileSync(
    path.join(migrationDir, 'manifest.json'),
    `${JSON.stringify(manifest, null, 2)}\n`,
    'utf8',
  );
}
